// src/lib/data.ts

export const artworks = [
  {  id: 1,
    title: "Pirate Invasion",
    description:
      "A majestic city of domes, arches, and towers faces the arrival of pirate ships under its stone bridge. Blending architectural fantasy with historical ambiance, this hand-drawn ink piece invites the viewer into a silent clash of beauty and rebellion.",
    medium: "Ink on cardboard",
    size: "37 x 25.5 cm.",
    price: "USD $299",
    available: true,
    category: "Architecture",
    image: "/invasion.jpg",
    alt: "Black ink drawing of an imaginary city being invaded by pirates.",
  },
  {
    id: 2,
    title: "Greystone Haven",
    description:
      "Nestled between quiet trees and winding paths, Greystone Haven depicts a village where nature and architecture intertwine. Curved rooftops, organic stairways, and a tree-born tower with a dragon sentinel evoke a timeless, magical retreat. Every stroke of ink reveals a hidden story within this peaceful sanctuary.",
    medium: "Pen and Ink on cardboard",
    size: "37 x 25.5 cm.",
    price: "USD $299",
    available: true,
    category: "Architecture",
    image: "/oldcity.jpg",
    alt: "Greystone Haven - A village where nature and architecture intertwine.",
  },
  {
    id: 3,
    title: "Dragonfly Fantasy",
    description: "Detailed ink drawing of a dragonfly hovering over abstract flora.",
    medium: "Pen and Ink",
    size: "30 x 30 cm.",
    price: "USD $170",
    available: true,
    category: "Nature",
    image: "/dragonfly.jpg",
    alt: "Ink illustration of a dragonfly surrounded by abstract flora."
  },
  
  {
      id: 4,
      title: "Sentient Trees",
      description: "Two sentient trees lean toward each other in a whimsical and mystical embrace.",
      medium: "Pen and Ink on cardboard",
      size: "42 x 29.5 cm.",
      price: "USD $199",
      available: true,
      category: "Nature",
      image: "/2arboles.png",
      alt: "Black ink drawing of two intertwined whimsical trees."
    },
   
    {
      id: 5,
      title: "The Geometry of Breath",
      image: "/armonic.jpg",
      category: "Geometric",
      medium: "Ink on paper",
      size: "",
      description:"An exploration of rhythm and balance, The Geometry of Breath evokes the cyclical and meditative nature of breathing. Composed entirely of fine intersecting lines, the swirling star-like form suggests a pulse—expanding and contracting in visual harmony. The minimalist design offers a quiet yet powerful sense of flow, inviting contemplation on the beauty of order, movement, and the invisible forces that connect all life.",
      price: "USD $150",
      available: true,
      alt: "The Geometry of Breath An exploration of rhythm and balance, The Geometry of Breath evokes the cyclical and meditative nature of breathing.",      
    },
    {
      id: 6,
      title: "Fat Cat",
      description:
        "A majestic feline sits in perfect stillness, its body composed of layered zentangle patterns—each paw, whisker, and stare drawn with intention. Fat Cat blends the charm of a domestic guardian with the commanding presence of a temple idol. Bold symmetry and rich textures turn this portrait into a symbol of watchful wisdom.",
      medium: "Pen and Ink on paper",
      size: "25x 29.5 cm.",
      price: "USD $",
      available: false,
      category: "Animals",
      image: "/cat.jpg",
      alt: "Fat Cat - A majestic feline sits in perfect stillness.",
    },
    
    
    {
      id: 7,
      title: "Geometric Exploration",
      description: "Bold composition mixing organic shapes and geometric forms.",
      medium: "Pen and Ink",
      size: "35 x 28 cm.",
      price: "USD $140",
      available: true,
      category: "geometric",
      image: "/geo.jpg",
      alt: "Intricate ink drawing combining geometric and organic patterns."
    },
    
    {
      id: 8,
      title: "Garden of Whispers",
      description: "Mystical garden scene with swirling, intricate floral designs.",
      medium: "Pen and Ink",
      size: "45 x 35 cm.",
      price: "USD $210",
      available: true,
      category: "Nature",
      image: "/garden.jpg",
      alt: "Detailed ink garden illustration with swirling flowers and vines."
    },
    {
      id: 9,
      title: "Mysterious Mandala",
      description: "Elaborate black ink mandala symbolizing balance and infinity.",
      medium: "Pen and Ink",
      size: "28 x 28 cm.",
      price: "USD $160",
      available: true,
      category: "geometric",
      image: "/mandala1.jpg",
      alt: "Black ink mandala artwork with intricate details."
    },
    {
      id: 10,
      title: "Ocean's Eye",
      description: "Circular abstract piece resembling an eye reflecting ocean waves.",
      medium: "Pen and Ink",
      size: "30 x 30 cm.",
      price: "USD $170",
      available: true,
      category: "Abstract",
      image: "/ojos.jpg",
      alt: "Abstract circular ink drawing resembling an eye and waves."
    },
    {
      id: 11,
      title: "One Piece Tribute",
      description: "Playful black ink tribute to One Piece's whimsical universe.",
      medium: "Pen and Ink",
      size: "40 x 30 cm.",
      price: "USD $190",
      available: true,
      category: "Fantasy",
      image: "/onepiece.jpg",
      alt: "Ink tribute artwork inspired by One Piece characters."
    },
    {
      id: 12,
      title: "Pink Panther",
      description:
        "A beloved pop icon reimagined through zentangle textures and surreal motion. Pink Panther bursts with personality as the famously cool feline balances with elegance and chaos, cigar in paw and smirk intact. The intricate linework and subtle pinks breathe new life into a classic figure—mischievous, sophisticated, and entirely unique.",
      medium: "Pen and Ink on paper",
      size:"29.7 × 42 cm (A3)",
      price: "USD $150",
      available: true,
      category: "Animals",
      image: "/pantera.jpg",
    },
    {
      id: 13,
      title: "Inkborne  ",
      image: "/horse2.jpg",
      category: "Animals",
      medium: "Ink on paper",
      size: "21 x 29.7 cm",
      description:"The soul of a horse captured through an elaborate dance of patterns. Inkborne evokes quiet strength, patience, and noble ancestry—etched into every line like the memory of wild plains beneath the skin.",
      price: "USD $150",
      available: true,
     
    },
    {
      id: 14,
      title: "Spirals of the Wild ",
      image: "/horse1.jpg",
      category: "Animals",
      medium: "Pen and ink on paper",
      size: "21 x 29.7 cm",
      description:"A majestic equine spirit rendered in intricate detail, Spirals of the Wild channels the raw energy of motion and instinct. Every strand of its mane twists with ancient rhythm, as if the wind itself whispers through a timeless dance of freedom.",
      price: "USD $150",
      available: true,
      alt: "Ink drawing of a galloping majestic horse."
    },
     
    {
      id: 15,
      title: "Sacred Orbit  ",
      image: "/mandala2.jpg",
      category: "Geometric",
      medium: "Pen and Ink on paper",
      size: "21 x 29.7 cm",
      description:"Sacred Orbit portrays a cosmic mandala encircled by rhythmic pulses and celestial orbs. Its balance and radial symmetry evoke the harmony of planetary systems, inviting viewers to contemplate the unseen geometry that shapes our universe.",
      price: "USD $150",
      available: true,
      alt: "Black ink mandala artwork with intricate details.",
    },
    {
      id: 16,
      title: "Moonlace",
      image: "/mandala3.jpg",
      category: "Geometric",
      medium: "Pen and Ink on paper",
      size: "21 x 29.7 cm",
      description:"Bathed in ethereal stillness, Moonlace emerges like a mandala dream conjured beneath the watchful eye of the moon. Its concentric rhythms echo ancient chants, and its filigreed lines seem to whisper secrets of celestial harmony. A mystical portal, both delicate and infinite.",
      price: "USD $150",
      available: true,
      alt: "Moonlace - Detailed black ink mandala with spirals and symmetry.",
    },
    {
      id: 17,
      title: "Silent Radiance ",
      image: "/mandala4.jpg",
      category: "Geometric",
      medium: "Pen and Ink on paper",
      size: "21 x 29.7 cm",
      description:"A sacred bloom wrapped in silence, Silent Radiance evokes the inner light that glows when all is still. The star-like symmetry and floral core pulse with quiet energy, like a whispered mantra echoing through space. A meditative geometry for the soul’s inner journey.",
      price: "USD $150",
      available: true,
      alt: "Silent Radiance - Detailed black ink mandala with spirals and symmetry.",
    },
    {
      id: 18,
      title: "The Watchcircle   ",
      image: "/mandala5.jpg",
      category: "Geometric",
      medium: "Pen and Ink on paper",
      size: "21 x 29.7 cm",
      description:"The Watchcircle spins with ancient rhythm and watchful presence. Its layered petals resemble ever-opening eyes, protectors of unseen realms. This hypnotic mandala invites contemplation on cycles, perception, and the unseen guardians that encircle us.",
      price: "USD $150",
      available: true,
      alt : "The Watchcircle - Detailed black ink mandala with spirals, rhythm  and symmetry.",
    },
    {
      id: 19,
      title: "Crowned Fury ",
      image: "/leon.jpg",
      category: "Animals",
      medium: "Ink on paper",
      size: "29.7 × 42 cm (A3 vertical)",
      description:"A regal beast roars with divine rage. Crowned Fury blends ornamental detail and raw emotion, portraying a lion crowned with power, wisdom, and primal energy. Each stroke in its mane whispers ancient tales of protection, rebellion, and inner fire.",
      price: "USD $250",
      available: true,
      alt: "Crowned Fury - Furious Lion;  King of all.",
     
    },
    
    {
      id: 20,
      title: "Medusa Bloom ",
      image: "/medusa.jpg",
      category: "Fantasy",
      medium: "Pen and ink on paper",
      size: "21 x 29.7 cm",
      description:"A hypnotic garden of twisting tendrils, Medusa Bloom evokes myth and movement. Each spiraled branch coils with energy, merging organic growth and symbolic chaos. It invites viewers to lose themselves in a surreal tangle of life, transformation, and hidden power.",
      price: "USD $150",
      alt: "Medusa Bloom - Detailed black ink mandala with spirals and symmetry.",
      available: true,
     
    },
    
    {
      id: 21,
      title: "Cathedral of Eyes ",
      image: "/ojos.jpg",
      category: "Fantasy",
      medium: "Pen and Ink on paper",
      size: "29.7 × 42 cm (A3 vertical)",
      description:"A mesmerizing tapestry of eyes, feathers, and symbols, Cathedral of Eyes resembles a divine guardian watching from a hidden realm. Each intricate element adds to the sense of sentient stillness, as if the being were silently judging and protecting. The layered textures evoke sacred geometry and dreamlike visions—a hypnotic portal into the unknown.",
      price: "USD $299",
      sold: false,
      available: true,
      alt: "Cathedral of Eyes - Detailed eyes with intricate details.",
    },
    
    
    {
      id: 22,
      title: " Cellular Echoes",
      image: "/circles.jpg",
      category: "Geometric",
      medium: "Pen and ink on paper",
      size: "21 x 29.7 cm",
      description:"Cellular Echoes explores the balance between form and flow through a tapestry of interlaced bubbles and cocoon-like shapes. Each sphere pulses with rhythm, inviting viewers to contemplate life at both microscopic and cosmic scales. The drawing plays with repetition, shadows, and patterns to evoke a sense of organized chaos—like echoes vibrating in a timeless void.",
      price: "USD $100",    
      available: true,
      alt: "Cellular Echoes - Detailed black ink mandala with spirals and symmetry.",
    },
      {
      id: 23,
      title: "Whispering Muse ",
      image: "/girl1.jpg",
      category: "Humans",
      medium: "Pen and ink on paper",
      size: "21 x 29.7 cm",
      description:"A serene female figure emerges from a swirl of intricate patterns, her closed eyes hinting at inner peace and deep thought. Whispering Muse celebrates the power of silence and feminine strength, expressed through a harmonious blend of texture, geometry, and botanical motifs flowing through her hair like whispered stories.",
      price: "USD $100",
      available: true,
      alt: "Whispering Muse - Detailed black ink girl with intricate details.",
    },
    
    {
      id: 24,
      title: "Zenspired ",
      image: "/girl2.jpg",
      category: "Humans",
      medium: "Pen and ink on paper",
      size: "21 x 29.7 cm",
      description:"Flowing with meditative calm, Zenspired portrays a woman whose hair cascades like rivers of geometric serenity. Each strand is a unique pattern, symbolizing the layered thoughts and emotions that shape inner peace. The composition invites contemplation, offering a visual mantra of quiet strength and balance.",
      price: "USD $100",
      available: true,
      alt: "Zenspired - Detailed black ink long haired girl with intricate details.",
    },
    
    {
      id: 25,
      title: "Braided Spirit ",
      image: "/girl3.jpg",
      category: "Humans",
      medium: "Pen and ink on paper",
      size: "21 x 29.7 cm",
      description:"Braided Spirit captures the essence of individuality woven through harmony. The subject’s intricate braids, composed of detailed textures and fluid patterns, echo inner strength and thoughtful complexity. A single earring and poised expression add subtle flair, celebrating confidence and feminine mystery in equal measure.",
      price: "USD $100",    
      available: true,
      alt: "Braided Spirit - Detailed black ink braided hair girl with intricate patterns.",
    },
    
    {
      id: 26,
      title: "Textures of Time",
      image: "/geo.jpg",
      category: "Geometric",
      medium: "Pen and ink on paper",
      size: "21 x 29.7 cm",
      description:"This hypnotic composition is a celebration of texture and rhythm. Each triangular slice radiating from the center contains its own unique pattern, symbolizing the multiplicity of moments and memories. Textures of Time invites the viewer to contemplate the intricacies hidden in repetition, and the harmony found in visual diversity.",
      price: "USD $100",
      available: true,
      alt: "Textures of Time - Detailed black ink mandala with spirals and symmetry.",
    },
    
    {
      id: 27,
      title: "Blizzard Buddy ",
      image: "/drag1.jpg",
      category: "Animals",
      medium: "Pen and Ink on paper",
      size: "21 x 29.7 cm",
      description:"A playful young dragon rides gleefully across the icy plains on a whimsical snowmobile. Blizzard Buddy combines fantasy with childhood joy, turning a mythical creature into a charming companion of winter adventures. Every scale and swirl carries texture and movement, drawing the viewer into a story of wonder and speed.",
      price: "USD $150",
      available: true,
      alt: "Blizzard Buddy - Playful dragon riding snowmobile.",
    },
    
    {
      id: 28,
      title: " Tiny Wyrm",
      image: "/drag2.jpg",
      category: "Animals",
      medium: "Pen and Ink on paper",
      size: "",
      description:"With wide, curious eyes and a soft expression, Tiny Wyrm captures the innocence of a young mythical beast. This dragon, perched with poised charm, invites the viewer into a moment of quiet connection. Intricate textures across its scales and horns give life and warmth to a creature often seen as fierce, reimagined here as a symbol of gentleness and wonder.",
      price: "USD $150",
      available: true,
      alt: "Tiny Wyrm - Playful dragon reimagined here as a symbol of gentleness and wonder.",
    },
    
    {
      id: 29,
      title: "Drake O’Gold ",
      image: "/drag3.jpg",
      category: "Animals",
      medium: "Ink on paper",
      size: "21 x 29.7 cm",
      description:"Drake O’Gold is a playful take on fantasy folklore, presenting a baby dragon dressed as a pirate. With a mischievous smile and wide, sparkling eyes, this charming creature exudes a spirit of adventure. Adorned in a skull-emblazoned hat and rich scale details, the drawing blends whimsy with craftsmanship, inviting viewers to imagine high-seas escapades in a world where dragons captain ships and treasure is found in laughter.",
      price: "USD $150",
      available: true,
      alt: "Drake O’Gold - Playful dragon dressed as a pirate.",
    },
    
    {
      id: 30,
      title: "Portal to the Inner Light",
    description: "A sacred spiral opens a path inward, inviting the soul to journey through layers of wisdom, transformation, and rebirth. A meditation on the infinite light that dwells within all beings.",
    medium: "Pen and Ink on paper",
    size: "42 x 29.5 cm",
    price: "USD $220",
    available: true,
    category: "geometric", // cambia Abstract por Sacred Geometry si prefieres
    image: "/hole.jpg",
    alt:" Portal to the Inner Light - A sacred spiral opens a path inward, inviting the soul to journey through layers of wisdom, transformation, and rebirth.",
    },
  
    {
      id: 31,
      title: "Warden Spirits ",
      image: "/clever1.jpg",
      category: "Animals",
      medium: "Pen and Ink on paper",
      size: "21 x 29.7 cm",
      description:"A fox and an owl, fused in intricate geometry, represent instinct and wisdom united. Their sacred bond whispers through feathers and fur — guardians of intuition, forever watching.",
      price: "USD $150",
      available: false,
      alt: "Warden Spirits - A fox and an owl, fused in intricate geometry, represent instinct and wisdom united.",
    },
    {
      id: 32,
      title: "Train to Hell",
      description:
        "A lone steam train emerges from a stone tunnel only to find its tracks vanishing into a cascading abyss of waterfalls and stacked boulders. A surreal vision of doom and descent, this piece captures the unsettling tension between progress and collapse — a journey with no return.",
  
      medium: "Ink on cardboard",
      size: "37 x 25.5 cm.",
      price: "USD $310",
      available: true,
      image: "/disaster.jpg",
      category: "Fantasy",
    },
    {
      id: 33,
      title: "Summer Garden ",
      image: "/garden.jpg",
      category: "Nature",
      medium: "Ink on paper",
      size: "21 x 29.7 cm",
      description:"A lush tangle of stylized blooms and abstract flora springs to life in Summer Garden. This intricate composition celebrates growth, complexity, and nature’s rhythmic chaos—where petals swirl, seeds dream, and the garden pulses with vibrant stillness.",
      price: "",
      available: false,
      alt: "Summer Garden - A lush tangle of stylized blooms and abstract flora springs to life.",
    },
    {
      id: 34,
      title: "Inkwoven Dreams",
      image: "/ink001.png",
      category: "Fantasy",
      medium: "Ink on paper",
      size: "21 x 29.7 cm",
      description:"A mesmerizing tapestry of interwoven patterns and surreal forms. Each fragment tells its own story, blending precision, imagination, and fluid motion in a dance of black ink on white canvas",
      price: "USD $150",
      available: false,
      alt: "Inkwoven Dreams - A mesmerizing tapestry of interwoven patterns and surreal forms.",
    },
    {
      id: 35,
      title: "Dragon Love",
      image: "/draglove.jpg",
      category: "Animals",
      medium: "Ink on paper",
      size: "29.7 × 42 cm (A3 vertical)",
      description: "Two aquatic dragons entwine in an elegant dance of symmetry and affection, sharing a single breath. Intricate textures and flowing lines evoke both movement and harmony, portraying a mystical underwater courtship with powerful emotion and silent intimacy.",
      price: "USD $150",
      available: false,
      alt: "Dragón Love - Two aquatic dragons entwine in an elegant dance of symmetry and affection, sharing a single breath.",
    },
    {
      id: 36,
      title: "Wolf",
      image: "/foxy.jpg",
      category: "Animals",
      medium: "Ink on paper",
      size: "29.7 × 42 cm (A3 vertical)",
      description: "Two aquatic dragons entwine in an elegant dance of symmetry and affection, sharing a single breath. Intricate textures and flowing lines evoke both movement and harmony, portraying a mystical underwater courtship with powerful emotion and silent intimacy.",
      price: "USD $250",
      available: false,
      alt: "Dragón Love - Two aquatic dragons entwine in an elegant dance of symmetry and affection, sharing a single breath.",
    },
    {
      id: 37,
      title: "Tiny Talon, Big Dreams",
      image: "/drag4.jpg",
      category: "Animals",
      medium: "Ink, marker, pen and coloring pencils",
      size: "29.7 × 42 cm (A3 vertical)",
      description: "Tiny Talon, Big Dreams celebrates a newborn dragon’s hopeful gaze, rendered entirely in fine-line ink. Intricate stippling and cross-hatching bring texture to its soft cheeks and unfolding wings, while exaggerated eyes convey boundless curiosity. This piece balances playful charm with technical precision, reminding us that even the smallest beginnings can harbor the grandest ambitions.",
      price: "USD $ 150",
      available: true,
      alt: "",
    },
    {
      id: 38,
      title: "Mr. Sun",
      image: "/sol.jpg",
      category: "geometric",
      medium: "Ink, marker, pen and coloring pencils",
      size: "29.7 × 42 cm (A3 vertical)",
      description: "Mr. Sun is a vibrant mandala that radiates warmth and intricate energy. Dominated by golden yellows, sunburst oranges, and earthy reds, the piece evokes the essence of sunlight and vitality. Its symmetrical design combines floral and tribal elements, forming a central bloom surrounded by complex patterns that resemble sunrays and organic shields. Accents of green and heart shapes bring balance and harmony, while the artist’s signature, 'Mabel', grounds the composition with a personal touch. This hand-drawn mandala celebrates the life-giving force of the sun with color, symmetry, and soul.",
      price: "USD $",
      available: true,
      alt: "",
    },
    {
      id: 39,
      title: "Mrs. Moon",
      image: "/luna.jpg",
      category: "geometric",
      medium: "Ink, marker, pen and coloring pencils",
      size: "29.7 × 42 cm (A3 vertical)",
      description: "Mr. Sun is a vibrant mandala that radiates warmth and intricate energy. Dominated by golden yellows, sunburst oranges, and earthy reds, the piece evokes the essence of sunlight and vitality. Its symmetrical design combines floral and tribal elements, forming a central bloom surrounded by complex patterns that resemble sunrays and organic shields. Accents of green and heart shapes bring balance and harmony, while the artist’s signature, 'Mabel', grounds the composition with a personal touch. This hand-drawn mandala celebrates the life-giving force of the sun with color, symmetry, and soul.",
      price: "USD $",
      available: true,
      alt: "",
    },
    
     {
      id: 40,
      title: "Baloon Fishy",
      image: "/globo.jpg",
      category: "geometric",
      medium: "Ink, marker, pen and coloring pencils",
      size: "29.7 × 42 cm (A3 vertical)",
      description: "A dance of lines and colors, this mandala echoes the gentle puff and graceful flow of a balloon fish, where each curve breathes life and each shade whispers of the sea",
      price: "USD $",
      available: true,
      alt: "",
    },
 {
      id: 41,
      title: "Golden Symphony",
      image: "/art1.jpg",
      category: "fantasy",
      medium: "Ink, marker, acrylics",
      size: "29.7 × 42 cm ",
      description: "This hand-colored ornamental design celebrates the elegance of classical motifs with a vibrant modern touch. The composition features interlaced scrolls, leafy flourishes, and floral accents, carefully balanced to create a sense of symmetry and harmony. Warm earthy browns, golden yellows, and lively greens blend with pops of red, infusing the artwork with both richness and vitality. The interplay of colors highlights the depth of the intricate patterns, transforming the piece into a visual symphony where tradition meets personal creativity",
      price: "USD $",
      available: true,
      alt: "",
    },
     {
      id: 42,
      title: "Celestial Mandala in Bloom",
      image: "/art2.jpg",
      category: "fantasy",
      medium: "Ink, marker, acrylics",
      size: "29.7 × 42 cm ",
      description: "This radiant mandala unfolds like a celestial garden, where deep navy blue and vibrant magenta meet golden arabesques in perfect harmony. Delicate pastel blossoms soften the intricate geometry, creating a balance between elegance and vitality. The interplay of rich colors and luminous gold accents evokes both opulence and serenity, transforming the pattern into a mesmerizing dance of symmetry and floral grace. A piece that invites contemplation, yet dazzles with its ornamental brilliance.",
      price: "USD $",
      available: true,
      alt: "",
    },
 {
      id: 43,
      title: "Garden of Radiant Symmetry",
      image: "/art3.jpg",
      category: "fantasy",
      medium: "Ink, marker, acrylics",
      size: "29.7 × 42 cm ",
      description: "This mandala blossoms with vibrant contrasts, where deep navy and crimson red embrace turquoise accents and golden flourishes. At its heart, a delicate floral star expands outward, framed by intricate petals and tiny blossoms in soft pastels. The balance between bold geometry and gentle floral motifs creates a sense of both energy and serenity. A celebration of harmony in motion, this piece transforms ornamental tradition into a living garden of color and light.",
      price: "USD $",
      available: true,
      alt: "",
    },
     {
      id: 44,
      title: "Heart of Royal Splendor",
      image: "/art4.jpg",
      category: "fantasy",
      medium: "Ink, marker, acrylics",
      size: "29.7 × 42 cm ",
      description: "This mandala radiates opulence with its bold interplay of crimson red, sapphire blue, and emerald green, all framed by golden filigree. At its center, an ornate floral medallion blooms with delicate pastel tones, expanding outward into heart-shaped motifs that pulse with vibrant energy. The symmetry is both regal and playful, balancing elegance with warmth. A piece that embodies timeless ornamentation, yet feels alive through its vivid colors and intricate details.",
      price: "USD $",
      available: true,
      alt: "",
    },
 {
      id: 45,
      title: "Radiant Harmony Mandala",
      image: "/art5.jpg",
      category: "Geometric",
      medium: "Ink, marker, acrylics",
      size: "29.7 × 42 cm ",
      description: "This hand-drawn mandala, titled Radiant Harmony, symbolizes the balance between complexity and tranquility. Through the use of vibrant colors—deep blues, lush greens, and warm pinks—the composition evokes both energy and serenity. Each concentric layer represents growth and inner connection, while the intricate floral and geometric motifs express the artist’s attention to symmetry and harmony. The fine detailing and bold contrasts highlight a meditative creative process, making this piece a celebration of mindfulness and artistic precision.",
      price: "USD $",
      available: true,
      alt: "",
    },
{
    id: 46,
    title: "Draglings",
    image: "/dragon.jpg",
    category: "Animals",
    medium: "Mixed Media ink and coloring pencil on paper",
    size:"42 × 29.7 cm (A3)",
    description: "Draglings- depicts Mama Drake with her three baby dragons in front of a distant castle. A lone monk watches from the left mountain, adding mystery to this tender, magical scene. ideal for collectors who appreciate detailed linework and mythical creatures", 
    price: "USD $",
    available: true,
    alt: "",
  },
{
    id: 48,
    title: "Ocean Serenity Mandala",
    image: "/art6.jpg",
    category: "Geometric",
    medium: "Mixed Media ink and coloring pencil on paper",
    size:"42 × 29.7 cm (A3)",
    description: "Ocean Serenity Mandala captures the calm strength of the sea through an intricate balance of blues, yellows, and whites. The detailed floral geometry radiates from the center like waves expanding in still water, symbolizing peace, introspection, and spiritual depth. Each layer unfolds in harmonious rhythm, reflecting both precision and fluidity. The cool color palette evokes a meditative atmosphere, inviting the viewer to pause, breathe, and immerse in tranquility.", 
    price: "USD $",
    available: true,
    alt: "",
  },
  {
    id: 49,
    title: "Celestial Bloom Mandala",
    image: "/art7.jpg",
    category: "Geometric",
    medium: "Mixed Media ink and coloring pencil on paper",
    size:"42 × 29.7 cm (A3)",
    description: "Celestial Bloom Mandala radiates vitality and cosmic balance through its rich interplay of colors and patterns. The artwork combines warm tones of red, orange, and gold with the serenity of blue, evoking the duality between energy and peace. Each petal-like motif unfolds from the center like a blooming flower, symbolizing growth, renewal, and harmony. The meticulous pointillist detailing enhances its texture and depth, reflecting patience and devotion in every stroke. This piece embodies a celebration of life, light, and the infinite rhythm of the universe.", 
    price: "USD $",
    available: true,
    alt: "",
  },
  ]
  