// src/lib/data.ts

export const artworks = [
  {
    id: 1,
    title: "Sentient Trees",
    description: "Two sentient trees lean toward each other in a whimsical and mystical embrace.",
    medium: "Pen and Ink on cardboard",
    size: "42 x 29.5 cm.",
    price: "USD $199",
    available: true,
    category: "Nature",
    image: "/arboles.png",
    alt: "Black ink drawing of two intertwined whimsical trees."
  },
  {
    id: 2,
    title: "Baby Dragons",
    description: "A playful scene featuring a family of baby dragons cuddling together.",
    medium: "Ink and Digital Color",
    size: "40 x 30 cm.",
    price: "USD $220",
    available: true,
    category: "Fantasy",
    image: "/baby drags.png",
    alt: "Cute baby dragons cuddling, illustrated in ink with soft colors."
  },
  {
    id: 3,
    title: "Harmonic Landscape",
    description: "A serene ink landscape blending natural patterns and geometric harmony.",
    medium: "Pen and Ink",
    size: "40 x 30 cm.",
    price: "USD $180",
    available: true,
    category: "Abstract",
    image: "/armonic.jpg",
    alt: "Harmonic black ink landscape with flowing geometric shapes."
  },
  {
    id: 4,
    title: "Flying Dragon",
    description: "A majestic dragon soaring through cloudy skies with powerful wings.",
    medium: "Pen and Ink",
    size: "40 x 30 cm.",
    price: "USD $250",
    available: true,
    category: "Fantasy",
    image: "/drag1.jpg",
    alt: "Black ink drawing of a dragon flying across the sky."
  },
  {
    id: 5,
    title: "Abstract Circles",
    description: "Hypnotic arrangement of overlapping black ink circles.",
    medium: "Pen and Ink",
    size: "30 x 30 cm.",
    price: "USD $120",
    available: true,
    category: "Abstract",
    image: "/circles.jpg",
    alt: "Abstract black ink circles intertwined together."
  },
  {
    id: 6,
    title: "Geometric Exploration",
    description: "Bold composition mixing organic shapes and geometric forms.",
    medium: "Pen and Ink",
    size: "35 x 28 cm.",
    price: "USD $140",
    available: true,
    category: "Geometry",
    image: "/geo.jpg",
    alt: "Intricate ink drawing combining geometric and organic patterns."
  },
  {
    id: 7,
    title: "Dragonfly Fantasy",
    description: "Detailed ink drawing of a dragonfly hovering over abstract flora.",
    medium: "Pen and Ink",
    size: "30 x 30 cm.",
    price: "USD $170",
    available: true,
    category: "Nature",
    image: "/dragonfly.jpg",
    alt: "Ink illustration of a dragonfly surrounded by abstract flora."
  },
  {
    id: 8,
    title: "Garden of Whispers",
    description: "Mystical garden scene with swirling, intricate floral designs.",
    medium: "Pen and Ink",
    size: "45 x 35 cm.",
    price: "USD $210",
    available: true,
    category: "Nature",
    image: "/garden.jpg",
    alt: "Detailed ink garden illustration with swirling flowers and vines."
  },
  {
    id: 9,
    title: "Mysterious Mandala",
    description: "Elaborate black ink mandala symbolizing balance and infinity.",
    medium: "Pen and Ink",
    size: "28 x 28 cm.",
    price: "USD $160",
    available: true,
    category: "Geometry",
    image: "/mandala1.jpg",
    alt: "Black ink mandala artwork with intricate details."
  },
  {
    id: 10,
    title: "Ocean's Eye",
    description: "Circular abstract piece resembling an eye reflecting ocean waves.",
    medium: "Pen and Ink",
    size: "30 x 30 cm.",
    price: "USD $170",
    available: true,
    category: "Abstract",
    image: "/ojos.jpg",
    alt: "Abstract circular ink drawing resembling an eye and waves."
  },
  {
    id: 11,
    title: "One Piece Tribute",
    description: "Playful black ink tribute to One Piece's whimsical universe.",
    medium: "Pen and Ink",
    size: "40 x 30 cm.",
    price: "USD $190",
    available: true,
    category: "Fantasy",
    image: "/onepiece.jpg",
    alt: "Ink tribute artwork inspired by One Piece characters."
  },
  {
    id: 12,
    title: "Whispering Pantera",
    description: "Elegant black panther emerging from abstract textures and lines.",
    medium: "Pen and Ink",
    size: "40 x 30 cm.",
    price: "USD $210",
    available: true,
    category: "Nature",
    image: "/pantera.jpg",
    alt: "Black ink panther emerging from abstract forms."
  },
  {
    id: 13,
    title: "Dreamy Girl I",
    description: "Delicate portrait of a dreamy girl surrounded by subtle textures.",
    medium: "Pen and Ink",
    size: "30 x 30 cm.",
    price: "USD $150",
    available: true,
    category: "Portrait",
    image: "/girl1.jpg",
    alt: "Black ink portrait of a girl with dreamlike atmosphere."
  },
  {
    id: 14,
    title: "Dreamy Girl II",
    description: "Second dreamy girl portrait evoking a sense of wonder and serenity.",
    medium: "Pen and Ink",
    size: "30 x 30 cm.",
    price: "USD $150",
    available: true,
    category: "Portrait",
    image: "/girl2.jpg",
    alt: "Dreamy black ink portrait of a girl looking serene."
  },
  {
    id: 15,
    title: "Majestic Horse I",
    description: "Majestic horse in full gallop drawn with flowing ink lines.",
    medium: "Pen and Ink",
    size: "35 x 28 cm.",
    price: "USD $180",
    available: true,
    category: "Animals",
    image: "/horse1.jpg",
    alt: "Ink drawing of a galloping majestic horse."
  },
  {
    id: 16,
    title: "Mandala Harmony",
    description: "Complex mandala with interconnected spirals symbolizing harmony.",
    medium: "Pen and Ink",
    size: "28 x 28 cm.",
    price: "USD $160",
    available: true,
    category: "Geometry",
    image: "/mandala3.jpg",
    alt: "Detailed black ink mandala with spirals and symmetry."
  },


  {
    id: 17,
    title: "Sacred Orbit  ",
    image: "/mandala2.jpg",
    category: "Geometric",
    medium: "Pen and Ink on paper",
    size: "21 x 29.7 cm",
    description:"Sacred Orbit portrays a cosmic mandala encircled by rhythmic pulses and celestial orbs. Its balance and radial symmetry evoke the harmony of planetary systems, inviting viewers to contemplate the unseen geometry that shapes our universe.",
    price: "USD $150",
    available: true,
    alt: "Black ink mandala artwork with intricate details.",
  },
  {
    id: 18,
    title: "Moonlace",
    image: "/mandala3.jpg",
    category: "Geometric",
    medium: "Pen and Ink on paper",
    size: "21 x 29.7 cm",
    description:"Bathed in ethereal stillness, Moonlace emerges like a mandala dream conjured beneath the watchful eye of the moon. Its concentric rhythms echo ancient chants, and its filigreed lines seem to whisper secrets of celestial harmony. A mystical portal, both delicate and infinite.",
    price: "USD $150",
    available: true,
    alt: "Moonlace - Detailed black ink mandala with spirals and symmetry.",
  },
  {
    id: 19,
    title: "Silent Radiance ",
    image: "/mandala4.jpg",
    category: "Geomeric",
    medium: "Pen and Ink on paper",
    size: "21 x 29.7 cm",
    description:"A sacred bloom wrapped in silence, Silent Radiance evokes the inner light that glows when all is still. The star-like symmetry and floral core pulse with quiet energy, like a whispered mantra echoing through space. A meditative geometry for the soul’s inner journey.",
    price: "USD $150",
    available: true,
    alt: "Silent Radiance - Detailed black ink mandala with spirals and symmetry.",
  },
  {
    id: 20,
    title: "The Watchcircle   ",
    image: "/mandala5.jpg",
    category: "Geometric",
    medium: "Pen and Ink on paper",
    size: "21 x 29.7 cm",
    description:"The Watchcircle spins with ancient rhythm and watchful presence. Its layered petals resemble ever-opening eyes, protectors of unseen realms. This hypnotic mandala invites contemplation on cycles, perception, and the unseen guardians that encircle us.",
    price: "USD $150",
    available: true,
    alt : "The Watchcircle - Detailed black ink mandala with spirals, rhythm  and symmetry.",
  },
  {
    id: 21,
    title: "Crowned Fury ",
    image: "/leon.jpg",
    category: "Animals",
    medium: "Ink on paper",
    size: "29.7 × 42 cm (A3 vertical)",
    description:"A regal beast roars with divine rage. Crowned Fury blends ornamental detail and raw emotion, portraying a lion crowned with power, wisdom, and primal energy. Each stroke in its mane whispers ancient tales of protection, rebellion, and inner fire.",
    price: "USD $250",
    available: true,
    alt: "Crowned Fury - Furious Lion;  King of all.",
   
  },
  
  {
    id: 22,
    title: "Medusa Bloom ",
    image: "/medusa.jpg",
    category: "Fantasy",
    medium: "Pen and ink on paper",
    size: "21 x 29.7 cm",
    description:"A hypnotic garden of twisting tendrils, Medusa Bloom evokes myth and movement. Each spiraled branch coils with energy, merging organic growth and symbolic chaos. It invites viewers to lose themselves in a surreal tangle of life, transformation, and hidden power.",
    price: "USD $150",
    alt: "Medusa Bloom - Detailed black ink mandala with spirals and symmetry.",
    available: true,
   
  },
  
  {
    id: 23,
    title: "Cathedral of Eyes ",
    image: "/ojos.jpg",
    category: "Fantasy",
    medium: "Pen and Ink on paper",
    size: "29.7 × 42 cm (A3 vertical)",
    description:"A mesmerizing tapestry of eyes, feathers, and symbols, Cathedral of Eyes resembles a divine guardian watching from a hidden realm. Each intricate element adds to the sense of sentient stillness, as if the being were silently judging and protecting. The layered textures evoke sacred geometry and dreamlike visions—a hypnotic portal into the unknown.",
    price: "USD $299",
    sold: false,
    available: true,
    alt: "Cathedral of Eyes - Detailed eyes with intricate details.",
  },
  
  {
    id: 24,
    title: " The Stairway Beyond ",
    image: "/dragonfly.jpg",
    category: "Animals",
    medium: "Pen and Ink on cardboard",
    size: "29.7 × 42 cm (A3 vertical)",
    description:"Winding stone steps lead the viewer into a fantastical forest where trees are homes, and dragons perch like watchful spirits. The Stairway Beyond is a delicate blend of fantasy and nature—an invitation to explore a secret world tucked between branches and myths. A dreamlike sense of stillness lingers, as though time has slowed down just enough to reveal magic.",
    price: "USD $250",    
    available: true,
    alt: "The Stairway Beyond - Fantasy forest with dragons perching.",
  },
  
  {
    id: 25,
    title: " Cellular Echoes",
    image: "/circles.jpg",
    category: "Geometric",
    medium: "Pen and ink on paper",
    size: "21 x 29.7 cm",
    description:"Cellular Echoes explores the balance between form and flow through a tapestry of interlaced bubbles and cocoon-like shapes. Each sphere pulses with rhythm, inviting viewers to contemplate life at both microscopic and cosmic scales. The drawing plays with repetition, shadows, and patterns to evoke a sense of organized chaos—like echoes vibrating in a timeless void.",
    price: "USD $100",    
    available: true,
    alt: "Cellular Echoes - Detailed black ink mandala with spirals and symmetry.",
  },
    {
    id: 26,
    title: "Whispering Muse ",
    image: "/girl1.jpg",
    category: "Humans",
    medium: "Pen and ink on paper",
    size: "21 x 29.7 cm",
    description:"A serene female figure emerges from a swirl of intricate patterns, her closed eyes hinting at inner peace and deep thought. Whispering Muse celebrates the power of silence and feminine strength, expressed through a harmonious blend of texture, geometry, and botanical motifs flowing through her hair like whispered stories.",
    price: "USD $100",
    available: true,
    alt: "Whispering Muse - Detailed black ink girl with intricate details.",
  },
  
  {
    id: 27,
    title: "Zenspired ",
    image: "/girl2.jpg",
    category: "Humans",
    medium: "Pen and ink on paper",
    size: "21 x 29.7 cm",
    description:"Flowing with meditative calm, Zenspired portrays a woman whose hair cascades like rivers of geometric serenity. Each strand is a unique pattern, symbolizing the layered thoughts and emotions that shape inner peace. The composition invites contemplation, offering a visual mantra of quiet strength and balance.",
    price: "USD $100",
    available: true,
    alt: "Zenspired - Detailed black ink long haired girl with intricate details.",
  },
  
  {
    id: 28,
    title: "Braided Spirit ",
    image: "/girl3.jpg",
    category: "Humans",
    medium: "Pen and ink on paper",
    size: "21 x 29.7 cm",
    description:"Braided Spirit captures the essence of individuality woven through harmony. The subject’s intricate braids, composed of detailed textures and fluid patterns, echo inner strength and thoughtful complexity. A single earring and poised expression add subtle flair, celebrating confidence and feminine mystery in equal measure.",
    price: "USD $100",    
    available: true,
    alt: "Braided Spirit - Detailed black ink braided hair girl with intricate patterns.",
  },
  
  {
    id: 29,
    title: "Textures of Time",
    image: "/geo.jpg",
    category: "Geometric",
    medium: "Pen and ink on paper",
    size: "21 x 29.7 cm",
    description:"This hypnotic composition is a celebration of texture and rhythm. Each triangular slice radiating from the center contains its own unique pattern, symbolizing the multiplicity of moments and memories. Textures of Time invites the viewer to contemplate the intricacies hidden in repetition, and the harmony found in visual diversity.",
    price: "USD $100",
    available: true,
    alt: "Textures of Time - Detailed black ink mandala with spirals and symmetry.",
  },
  
  {
    id: 30,
    title: "Blizzard Buddy ",
    image: "/drag1.jpg",
    category: "Animals",
    medium: "Pen and Ink on paper",
    size: "21 x 29.7 cm",
    description:"A playful young dragon rides gleefully across the icy plains on a whimsical snowmobile. Blizzard Buddy combines fantasy with childhood joy, turning a mythical creature into a charming companion of winter adventures. Every scale and swirl carries texture and movement, drawing the viewer into a story of wonder and speed.",
    price: "USD $150",
    available: true,
    alt: "Blizzard Buddy - Playful dragon riding snowmobile.",
  },
  
  {
    id: 31,
    title: " Tiny Wyrm",
    image: "/drag2.jpg",
    category: "Animals",
    medium: "Pen and Ink on paper",
    size: "",
    description:"With wide, curious eyes and a soft expression, Tiny Wyrm captures the innocence of a young mythical beast. This dragon, perched with poised charm, invites the viewer into a moment of quiet connection. Intricate textures across its scales and horns give life and warmth to a creature often seen as fierce, reimagined here as a symbol of gentleness and wonder.",
    price: "USD $150",
    available: true,
    alt: "Tiny Wyrm - Playful dragon reimagined here as a symbol of gentleness and wonder.",
  },
  
  {
    id: 32,
    title: "Drake O’Gold ",
    image: "/drag3.jpg",
    category: "Animals",
    medium: "Ink on paper",
    size: "21 x 29.7 cm",
    description:"Drake O’Gold is a playful take on fantasy folklore, presenting a baby dragon dressed as a pirate. With a mischievous smile and wide, sparkling eyes, this charming creature exudes a spirit of adventure. Adorned in a skull-emblazoned hat and rich scale details, the drawing blends whimsy with craftsmanship, inviting viewers to imagine high-seas escapades in a world where dragons captain ships and treasure is found in laughter.",
    price: "USD $150",
    available: true,
    alt: "Drake O’Gold - Playful dragon dressed as a pirate.",
  },
  
  {
    id: 33,
    title: "The Geometry of Breath",
    image: "/armonic.jpg",
    category: "Geometric",
    medium: "Ink on paper",
    size: "",
    description:"An exploration of rhythm and balance, The Geometry of Breath evokes the cyclical and meditative nature of breathing. Composed entirely of fine intersecting lines, the swirling star-like form suggests a pulse—expanding and contracting in visual harmony. The minimalist design offers a quiet yet powerful sense of flow, inviting contemplation on the beauty of order, movement, and the invisible forces that connect all life.",
    price: "USD $150",
    available: true,
    alt: "The Geometry of Breath An exploration of rhythm and balance, The Geometry of Breath evokes the cyclical and meditative nature of breathing.",      
  },
]
